// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("AWright18.PipeTo")]
[assembly: AssemblyDescriptionAttribute("Allows Piping of function results to other functions")]
[assembly: GuidAttribute("E8C6B039-E310-41FE-9B83-1E163739CD9A")]
[assembly: AssemblyProductAttribute("AWright18.PipeTo")]
[assembly: AssemblyCopyrightAttribute("2016")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-unstable.3+Branch.develop.Sha.e1a39f3d22c46939f435871b814c00d13fbe4a2f")]
[assembly: AssemblyMetadataAttribute("githash","e1a39f3d22c46939f435871b814c00d13fbe4a2f")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
        internal const string InformationalVersion = "0.1.0-unstable.3+Branch.develop.Sha.e1a39f3d22c46939f435871b814c00d13fbe4a2f";
    }
}
